// Code generated by goctl. DO NOT EDIT.
// Source: userinfo.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/internal/logic"
	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/internal/svc"
	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/pb"
)

type AccountCenterClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountCenterClientServer
}

func NewAccountCenterClientServer(svcCtx *svc.ServiceContext) *AccountCenterClientServer {
	return &AccountCenterClientServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountCenterClientServer) GetUserType(ctx context.Context, in *pb.GetUserTypeReq) (*pb.GetUserTypeResp, error) {
	l := logic.NewGetUserTypeLogic(ctx, s.svcCtx)
	return l.GetUserType(in)
}
