// Code generated by goctl. DO NOT EDIT.
// Source: userinfo.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/internal/logic"
	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/internal/svc"
	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/pb"
)

type UserInfoClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserInfoClientServer
}

func NewUserInfoClientServer(svcCtx *svc.ServiceContext) *UserInfoClientServer {
	return &UserInfoClientServer{
		svcCtx: svcCtx,
	}
}

func (s *UserInfoClientServer) GetUserType(ctx context.Context, in *pb.GetUserTypeReq) (*pb.GetUserTypeResp, error) {
	l := logic.NewGetUserTypeLogic(ctx, s.svcCtx)
	return l.GetUserType(in)
}
