// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: adjust.proto

package adjust

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdjustAdmissionstatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdmissionStatus string `protobuf:"bytes,1,opt,name=AdmissionStatus,proto3" json:"AdmissionStatus,omitempty"`
}

func (x *AdjustAdmissionstatusReq) Reset() {
	*x = AdjustAdmissionstatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adjust_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjustAdmissionstatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustAdmissionstatusReq) ProtoMessage() {}

func (x *AdjustAdmissionstatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_adjust_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustAdmissionstatusReq.ProtoReflect.Descriptor instead.
func (*AdjustAdmissionstatusReq) Descriptor() ([]byte, []int) {
	return file_adjust_proto_rawDescGZIP(), []int{0}
}

func (x *AdjustAdmissionstatusReq) GetAdmissionStatus() string {
	if x != nil {
		return x.AdmissionStatus
	}
	return ""
}

type AdjustAdmissionstatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
}

func (x *AdjustAdmissionstatusResp) Reset() {
	*x = AdjustAdmissionstatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adjust_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjustAdmissionstatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustAdmissionstatusResp) ProtoMessage() {}

func (x *AdjustAdmissionstatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_adjust_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustAdmissionstatusResp.ProtoReflect.Descriptor instead.
func (*AdjustAdmissionstatusResp) Descriptor() ([]byte, []int) {
	return file_adjust_proto_rawDescGZIP(), []int{1}
}

func (x *AdjustAdmissionstatusResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_adjust_proto protoreflect.FileDescriptor

var file_adjust_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x18, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x41, 0x64, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2f, 0x0a, 0x19,
	0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x32, 0x66, 0x0a,
	0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x5c, 0x0a, 0x15, 0x41, 0x64, 0x6a, 0x75, 0x73,
	0x74, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x20, 0x2e, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74,
	0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x6a, 0x75,
	0x73, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x61, 0x64, 0x6a, 0x75, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adjust_proto_rawDescOnce sync.Once
	file_adjust_proto_rawDescData = file_adjust_proto_rawDesc
)

func file_adjust_proto_rawDescGZIP() []byte {
	file_adjust_proto_rawDescOnce.Do(func() {
		file_adjust_proto_rawDescData = protoimpl.X.CompressGZIP(file_adjust_proto_rawDescData)
	})
	return file_adjust_proto_rawDescData
}

var file_adjust_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adjust_proto_goTypes = []interface{}{
	(*AdjustAdmissionstatusReq)(nil),  // 0: adjust.AdjustAdmissionstatusReq
	(*AdjustAdmissionstatusResp)(nil), // 1: adjust.AdjustAdmissionstatusResp
}
var file_adjust_proto_depIdxs = []int32{
	0, // 0: adjust.Modify.AdjustAdmissionstatus:input_type -> adjust.AdjustAdmissionstatusReq
	1, // 1: adjust.Modify.AdjustAdmissionstatus:output_type -> adjust.AdjustAdmissionstatusResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adjust_proto_init() }
func file_adjust_proto_init() {
	if File_adjust_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adjust_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjustAdmissionstatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adjust_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjustAdmissionstatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adjust_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adjust_proto_goTypes,
		DependencyIndexes: file_adjust_proto_depIdxs,
		MessageInfos:      file_adjust_proto_msgTypes,
	}.Build()
	File_adjust_proto = out.File
	file_adjust_proto_rawDesc = nil
	file_adjust_proto_goTypes = nil
	file_adjust_proto_depIdxs = nil
}
