// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: adjust.proto

package adjust

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Modify_AdjustAdmissionstatus_FullMethodName = "/adjust.Modify/AdjustAdmissionstatus"
)

// ModifyClient is the client API for Modify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModifyClient interface {
	AdjustAdmissionstatus(ctx context.Context, in *AdjustAdmissionstatusReq, opts ...grpc.CallOption) (*AdjustAdmissionstatusResp, error)
}

type modifyClient struct {
	cc grpc.ClientConnInterface
}

func NewModifyClient(cc grpc.ClientConnInterface) ModifyClient {
	return &modifyClient{cc}
}

func (c *modifyClient) AdjustAdmissionstatus(ctx context.Context, in *AdjustAdmissionstatusReq, opts ...grpc.CallOption) (*AdjustAdmissionstatusResp, error) {
	out := new(AdjustAdmissionstatusResp)
	err := c.cc.Invoke(ctx, Modify_AdjustAdmissionstatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModifyServer is the server API for Modify service.
// All implementations must embed UnimplementedModifyServer
// for forward compatibility
type ModifyServer interface {
	AdjustAdmissionstatus(context.Context, *AdjustAdmissionstatusReq) (*AdjustAdmissionstatusResp, error)
	mustEmbedUnimplementedModifyServer()
}

// UnimplementedModifyServer must be embedded to have forward compatible implementations.
type UnimplementedModifyServer struct {
}

func (UnimplementedModifyServer) AdjustAdmissionstatus(context.Context, *AdjustAdmissionstatusReq) (*AdjustAdmissionstatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustAdmissionstatus not implemented")
}
func (UnimplementedModifyServer) mustEmbedUnimplementedModifyServer() {}

// UnsafeModifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModifyServer will
// result in compilation errors.
type UnsafeModifyServer interface {
	mustEmbedUnimplementedModifyServer()
}

func RegisterModifyServer(s grpc.ServiceRegistrar, srv ModifyServer) {
	s.RegisterService(&Modify_ServiceDesc, srv)
}

func _Modify_AdjustAdmissionstatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustAdmissionstatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModifyServer).AdjustAdmissionstatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Modify_AdjustAdmissionstatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModifyServer).AdjustAdmissionstatus(ctx, req.(*AdjustAdmissionstatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Modify_ServiceDesc is the grpc.ServiceDesc for Modify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Modify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adjust.Modify",
	HandlerType: (*ModifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdjustAdmissionstatus",
			Handler:    _Modify_AdjustAdmissionstatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adjust.proto",
}
