// Code generated by goctl. DO NOT EDIT.
// Source: adjust.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/adjust/adjust"
	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/adjust/internal/logic"
	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/adjust/internal/svc"
)

type ModifyServer struct {
	svcCtx *svc.ServiceContext
	adjust.UnimplementedModifyServer
}

func NewModifyServer(svcCtx *svc.ServiceContext) *ModifyServer {
	return &ModifyServer{
		svcCtx: svcCtx,
	}
}

func (s *ModifyServer) AdjustAdmissionstatus(ctx context.Context, in *adjust.AdjustAdmissionstatusReq) (*adjust.AdjustAdmissionstatusResp, error) {
	l := logic.NewAdjustAdmissionstatusLogic(ctx, s.svcCtx)
	return l.AdjustAdmissionstatus(in)
}
