// Code generated by goctl. DO NOT EDIT.
package model

import (
	"MuXiFresh-Be-2.0/app/userauth/model"
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type formModel interface {
	Insert(ctx context.Context, data *Form) error
	FindOne(ctx context.Context, id string) (*Form, error)
	Update(ctx context.Context, data *Form) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultFormModel struct {
	conn *mon.Model
}

func newDefaultFormModel(conn *mon.Model) *defaultFormModel {
	return &defaultFormModel{conn: conn}
}

func (m *defaultFormModel) Insert(ctx context.Context, data *Form) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultFormModel) FindOne(ctx context.Context, id string) (*Form, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, model.ErrInvalidObjectId
	}

	var data Form

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, model.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFormModel) Update(ctx context.Context, data *Form) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultFormModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, model.ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
