// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adjust "MuXiFresh-Be-2.0/app/modify/cmd/api/internal/handler/adjust"
	modify "MuXiFresh-Be-2.0/app/modify/cmd/api/internal/handler/modify"
	"MuXiFresh-Be-2.0/app/modify/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/modify/:id/:Email",
				Handler: modify.ModifytheUsertypeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/modify/:Avatar",
				Handler: modify.ModifytheUseravatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/modify/:NickName",
				Handler: modify.ModifytheUsernameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/adjust",
				Handler: adjust.AdjustAdmissionstatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/task"),
	)
}
