// Code generated by goctl. DO NOT EDIT.
// Source: userinfo.proto

package userinfoclient

import (
	"context"

	"MuXiFresh-Be-2.0/app/userauth/cmd/rpc/userinfo/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserTypeReq  = pb.GetUserTypeReq
	GetUserTypeResp = pb.GetUserTypeResp

	UserInfoClient interface {
		GetUserType(ctx context.Context, in *GetUserTypeReq, opts ...grpc.CallOption) (*GetUserTypeResp, error)
	}

	defaultUserInfoClient struct {
		cli zrpc.Client
	}
)

func NewUserInfoClient(cli zrpc.Client) UserInfoClient {
	return &defaultUserInfoClient{
		cli: cli,
	}
}

func (m *defaultUserInfoClient) GetUserType(ctx context.Context, in *GetUserTypeReq, opts ...grpc.CallOption) (*GetUserTypeResp, error) {
	client := pb.NewUserInfoClientClient(m.cli.Conn())
	return client.GetUserType(ctx, in, opts...)
}
