// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"MuXiFresh-Be-2.0/app/review/cmd/api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/review",
				Handler: GetReviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/review/admission_status",
				Handler: SetAdmissionStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
