// Code generated by goctl. DO NOT EDIT.
// Source: form.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/form/rpc/internal/logic"
	"MuXiFresh-Be-2.0/app/form/rpc/internal/svc"
	"MuXiFresh-Be-2.0/app/form/rpc/pb"
)

type EntryFormClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEntryFormClientServer
}

func NewEntryFormClientServer(svcCtx *svc.ServiceContext) *EntryFormClientServer {
	return &EntryFormClientServer{
		svcCtx: svcCtx,
	}
}

func (s *EntryFormClientServer) JudgeUser(ctx context.Context, in *pb.ClickReq) (*pb.ClickResp, error) {
	l := logic.NewJudgeUserLogic(ctx, s.svcCtx)
	return l.JudgeUser(in)
}

func (s *EntryFormClientServer) CreateForm(ctx context.Context, in *pb.CreateReq) (*pb.CreateResp, error) {
	l := logic.NewCreateFormLogic(ctx, s.svcCtx)
	return l.CreateForm(in)
}

func (s *EntryFormClientServer) UpdateForm(ctx context.Context, in *pb.CreateReq) (*pb.CreateResp, error) {
	l := logic.NewUpdateFormLogic(ctx, s.svcCtx)
	return l.UpdateForm(in)
}

func (s *EntryFormClientServer) CheckForm(ctx context.Context, in *pb.CheckReq) (*pb.CheckResp, error) {
	l := logic.NewCheckFormLogic(ctx, s.svcCtx)
	return l.CheckForm(in)
}
