// Code generated by goctl. DO NOT EDIT.
// Source: assignment.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/task/cmd/rpc/assignment/internal/logic"
	"MuXiFresh-Be-2.0/app/task/cmd/rpc/assignment/internal/svc"
	"MuXiFresh-Be-2.0/app/task/cmd/rpc/assignment/pb"
)

type AssignmentClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAssignmentClientServer
}

func NewAssignmentClientServer(svcCtx *svc.ServiceContext) *AssignmentClientServer {
	return &AssignmentClientServer{
		svcCtx: svcCtx,
	}
}

func (s *AssignmentClientServer) GetAssignmentList(ctx context.Context, in *pb.GetAssignmentListReq) (*pb.GetAssignmentListResp, error) {
	l := logic.NewGetAssignmentListLogic(ctx, s.svcCtx)
	return l.GetAssignmentList(in)
}

func (s *AssignmentClientServer) GetAssignmentInfo(ctx context.Context, in *pb.GetAssignmentInfoReq) (*pb.GetAssignmentInfoResp, error) {
	l := logic.NewGetAssignmentInfoLogic(ctx, s.svcCtx)
	return l.GetAssignmentInfo(in)
}

func (s *AssignmentClientServer) SetAssignment(ctx context.Context, in *pb.SetAssignmentReq) (*pb.SetAssignmentResp, error) {
	l := logic.NewSetAssignmentLogic(ctx, s.svcCtx)
	return l.SetAssignment(in)
}
