// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MuxiFresh2.0/MuXiFresh-Be-2.0/app/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group",
				Handler: GetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2"),
	)
}
