// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	VerifyCode string `json:"verify_code"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type LoginReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type AuthPassChangeReq struct {
	Email      string `json:"email"`
	VerifyCode string `json:"verify_code"`
}

type AuthPassChangeResp struct {
	AuthChPassToken string `json:"auth_ch_pass_token"`
}

type PassChangeReq struct {
	Password        string `json:"password"`
	AuthChPassToken string `header:"Authorization"`
}

type PassChangeResp struct {
	Flag bool `json:"flag"`
}

type VerifyTokenReq struct {
	Token string `header:"Authorization"`
}

type VerifyTokenResp struct {
	Flag bool `json:"flag"`
}

type SendEmailCodeReq struct {
	Email string `json:"email"`
	Type  string `json:"type,options=[auth_register,auth_ch_pass]"`
}

type SendEmailCodeResp struct {
	Flag bool `json:"flag"`
}

type GetCaptchaResp struct {
	ImageBase64 string `json:"image_base64"`
	ImageID     string `json:"image_id"`
}

type VerifyCaptchaReq struct {
	ImageID    string `json:"image_id"`
	VerifyCode string `json:"verify_code"`
}

type VerifyCaptchaResp struct {
	Flag bool `json:"flag"`
}

type GetQNTokenReq struct {
	Token string `header:"Authorization"`
}

type GetQNTokenResp struct {
	QNToken string `json:"QiniuToken"`
}

type BindStudentIDReq struct {
	Token      string `header:"Authorization"`
	StdudentID string `json:"student_id"`
	Password   string `json:"password"`
}

type BindStudentIDResp struct {
	Flag bool `json:"flag"`
}

type CcnuLoginReq struct {
	StdudentID string `json:"student_id"`
	Password   string `json:"password"`
}

type CcnuLoginResp struct {
	Token string `json:"token"`
}
