// Code generated by goctl. DO NOT EDIT.
// Source: intro.proto

package introclient

import (
	"context"

	"MuXiFresh-Be-2.0/app/intro/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GroupIntroReq   = pb.GroupIntroReq
	GroupIntroResp  = pb.GroupIntroResp
	RecruitInfoReq  = pb.RecruitInfoReq
	RecruitInfoResp = pb.RecruitInfoResp

	IntroClient interface {
		GetGroupIntro(ctx context.Context, in *GroupIntroReq, opts ...grpc.CallOption) (*GroupIntroResp, error)
		GetRecruitInfo(ctx context.Context, in *RecruitInfoReq, opts ...grpc.CallOption) (*RecruitInfoResp, error)
	}

	defaultIntroClient struct {
		cli zrpc.Client
	}
)

func NewIntroClient(cli zrpc.Client) IntroClient {
	return &defaultIntroClient{
		cli: cli,
	}
}

func (m *defaultIntroClient) GetGroupIntro(ctx context.Context, in *GroupIntroReq, opts ...grpc.CallOption) (*GroupIntroResp, error) {
	client := pb.NewIntroClientClient(m.cli.Conn())
	return client.GetGroupIntro(ctx, in, opts...)
}

func (m *defaultIntroClient) GetRecruitInfo(ctx context.Context, in *RecruitInfoReq, opts ...grpc.CallOption) (*RecruitInfoResp, error) {
	client := pb.NewIntroClientClient(m.cli.Conn())
	return client.GetRecruitInfo(ctx, in, opts...)
}
