// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MuXiFresh-Be-2.0/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/:id",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id",
				Handler: SetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/:id/type",
				Handler: SetUserTypeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin-list",
				Handler: GetAdminListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2"),
	)
}
