// Code generated by goctl. DO NOT EDIT.
// Source: assignment.proto

package assignmentclient

import (
	"context"

	"MuXiFresh-Be-2.0/app/task/cmd/rpc/assignment/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAssignmentInfoReq  = pb.GetAssignmentInfoReq
	GetAssignmentInfoResp = pb.GetAssignmentInfoResp
	GetAssignmentListReq  = pb.GetAssignmentListReq
	GetAssignmentListResp = pb.GetAssignmentListResp
	SetAssignmentReq      = pb.SetAssignmentReq
	SetAssignmentResp     = pb.SetAssignmentResp
	Title                 = pb.Title

	AssignmentClient interface {
		GetAssignmentList(ctx context.Context, in *GetAssignmentListReq, opts ...grpc.CallOption) (*GetAssignmentListResp, error)
		GetAssignmentInfo(ctx context.Context, in *GetAssignmentInfoReq, opts ...grpc.CallOption) (*GetAssignmentInfoResp, error)
		SetAssignment(ctx context.Context, in *SetAssignmentReq, opts ...grpc.CallOption) (*SetAssignmentResp, error)
	}

	defaultAssignmentClient struct {
		cli zrpc.Client
	}
)

func NewAssignmentClient(cli zrpc.Client) AssignmentClient {
	return &defaultAssignmentClient{
		cli: cli,
	}
}

func (m *defaultAssignmentClient) GetAssignmentList(ctx context.Context, in *GetAssignmentListReq, opts ...grpc.CallOption) (*GetAssignmentListResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.GetAssignmentList(ctx, in, opts...)
}

func (m *defaultAssignmentClient) GetAssignmentInfo(ctx context.Context, in *GetAssignmentInfoReq, opts ...grpc.CallOption) (*GetAssignmentInfoResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.GetAssignmentInfo(ctx, in, opts...)
}

func (m *defaultAssignmentClient) SetAssignment(ctx context.Context, in *SetAssignmentReq, opts ...grpc.CallOption) (*SetAssignmentResp, error) {
	client := pb.NewAssignmentClientClient(m.cli.Conn())
	return client.SetAssignment(ctx, in, opts...)
}
