// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MuxiFresh2.0/MuXiFresh-Be-2.0/app/test/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/test",
				Handler: UserTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/test/result",
				Handler: CheckTestResultHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2"),
	)
}
