// Code generated by goctl. DO NOT EDIT.
// Source: modify.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/modify/internal/logic"
	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/modify/internal/svc"
	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/modify/modify"
)

type ModifyServer struct {
	svcCtx *svc.ServiceContext
	modify.UnimplementedModifyServer
}

func NewModifyServer(svcCtx *svc.ServiceContext) *ModifyServer {
	return &ModifyServer{
		svcCtx: svcCtx,
	}
}

func (s *ModifyServer) ModifytheUsertype(ctx context.Context, in *modify.ModifytheUsertypeReq) (*modify.ModifytheUsertypeResp, error) {
	l := logic.NewModifytheUsertypeLogic(ctx, s.svcCtx)
	return l.ModifytheUsertype(in)
}

func (s *ModifyServer) ModifytheUseravatar(ctx context.Context, in *modify.ModifytheUseravatarReq) (*modify.ModifytheUseravatarResp, error) {
	l := logic.NewModifytheUseravatarLogic(ctx, s.svcCtx)
	return l.ModifytheUseravatar(in)
}

func (s *ModifyServer) ModifytheUsername(ctx context.Context, in *modify.ModifytheUsernameReq) (*modify.ModifytheUsernameResp, error) {
	l := logic.NewModifytheUsernameLogic(ctx, s.svcCtx)
	return l.ModifytheUsername(in)
}
