// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"
	"usercenter-rpc/internal/logic"
	"usercenter-rpc/internal/svc"
	"usercenter-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func (s *UsercenterServer) GetVerificationCode(ctx context.Context, request *pb2.VerificationCodeRequest) (*pb2.VerificationCodeResponse, error) {
	//TODO implement me
	panic("implement me")
}

func (s *UsercenterServer) Register(ctx context.Context, request *pb2.RegisterRequest) (*pb2.RegisterResponse, error) {
	//TODO implement me
	panic("implement me")
}

func (s *UsercenterServer) GetInfo(ctx context.Context, request *pb2.GetInfoRequest) (*pb2.GetInfoResponse, error) {
	//TODO implement me
	panic("implement me")
}

func (s *UsercenterServer) mustEmbedUnimplementedUsercenterServer() {
	//TODO implement me
	panic("implement me")
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) GetVerificationCode(ctx context.Context, in *pb.VerificationCodeRequest) (*pb.VerificationCodeResponse, error) {
	l := logic.NewGetVerificationCodeLogic(ctx, s.svcCtx)
	return l.GetVerificationCode(in)
}

func (s *UsercenterServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UsercenterServer) GetInfo(ctx context.Context, in *pb.GetInfoRequest) (*pb.GetInfoResponse, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}
