// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"MuXiFresh-Be-2.0/app/schedule/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/schedule/create",
				Handler: CreateScheduleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/schedule",
				Handler: CheckHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2"),
	)
}
