// Code generated by goctl. DO NOT EDIT.
package types

type CreateReq struct {
	Authorization string `json:"Authorization"`
}

type CreateResp struct {
	Flag bool `json:"flag"`
}

type CheckReq struct {
	Authorization string `json:"Authorization"`
	ScheduleID    string `json:"Schedule_id"`
}

type CheckResp struct {
	Name            string `json:"name"`
	School          string `json:"school"`
	Major           string `json:"major"`
	Group           string `json:"group"`
	EntryFormStatus string `json:"entry_form_status"`
	AdmissionStatus string `json:"admission_status"`
}
