// Code generated by goctl. DO NOT EDIT.
// Source: intro.proto

package getclient

import (
	pb2 "MuxiFresh2.0/MuXiFresh-Be-2.0/app/group/rpc/pb"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetReq  = pb2.GetReq
	GetResp = pb2.GetResp

	GetClient interface {
		GetGroupIntro(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	}

	defaultGetClient struct {
		cli zrpc.Client
	}
)

func NewGetClient(cli zrpc.Client) GetClient {
	return &defaultGetClient{
		cli: cli,
	}
}

func (m *defaultGetClient) GetGroupIntro(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	client := pb2.NewGetClientClient(m.cli.Conn())
	return client.GetGroupIntro(ctx, in, opts...)
}
