// Code generated by goctl. DO NOT EDIT.
// Source: submission.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/task/cmd/rpc/submission/internal/logic"
	"MuXiFresh-Be-2.0/app/task/cmd/rpc/submission/internal/svc"
	"MuXiFresh-Be-2.0/app/task/cmd/rpc/submission/pb"
)

type SubmissionClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSubmissionClientServer
}

func NewSubmissionClientServer(svcCtx *svc.ServiceContext) *SubmissionClientServer {
	return &SubmissionClientServer{
		svcCtx: svcCtx,
	}
}

func (s *SubmissionClientServer) GetMySubmissionStatus(ctx context.Context, in *pb.GetMySubmissionStatusReq) (*pb.GetMySubmissionStatusResp, error) {
	l := logic.NewGetMySubmissionStatusLogic(ctx, s.svcCtx)
	return l.GetMySubmissionStatus(in)
}

func (s *SubmissionClientServer) SetSubmission(ctx context.Context, in *pb.SetSubmissionReq) (*pb.SetSubmissionResp, error) {
	l := logic.NewSetSubmissionLogic(ctx, s.svcCtx)
	return l.SetSubmission(in)
}

func (s *SubmissionClientServer) GetSubmissionInfo(ctx context.Context, in *pb.GetSubmissionInfoReq) (*pb.GetSubmissionInfoResp, error) {
	l := logic.NewGetSubmissionInfoLogic(ctx, s.svcCtx)
	return l.GetSubmissionInfo(in)
}

func (s *SubmissionClientServer) GetAllSubmissionStatus(ctx context.Context, in *pb.GetAllSubmissionStatusReq) (*pb.GetAllSubmissionStatusResp, error) {
	l := logic.NewGetAllSubmissionStatusLogic(ctx, s.svcCtx)
	return l.GetAllSubmissionStatus(in)
}
