// Code generated by goctl. DO NOT EDIT.
// Source: adjust.proto

package modify

import (
	"context"

	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/adjust/adjust"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdjustAdmissionstatusReq  = adjust.AdjustAdmissionstatusReq
	AdjustAdmissionstatusResp = adjust.AdjustAdmissionstatusResp

	Modify interface {
		AdjustAdmissionstatus(ctx context.Context, in *AdjustAdmissionstatusReq, opts ...grpc.CallOption) (*AdjustAdmissionstatusResp, error)
	}

	defaultModify struct {
		cli zrpc.Client
	}
)

func NewModify(cli zrpc.Client) Modify {
	return &defaultModify{
		cli: cli,
	}
}

func (m *defaultModify) AdjustAdmissionstatus(ctx context.Context, in *AdjustAdmissionstatusReq, opts ...grpc.CallOption) (*AdjustAdmissionstatusResp, error) {
	client := adjust.NewModifyClient(m.cli.Conn())
	return client.AdjustAdmissionstatus(ctx, in, opts...)
}
