// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: accountCenter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountCenterClient_Register_FullMethodName      = "/accountCenter.accountCenterClient/Register"
	AccountCenterClient_Login_FullMethodName         = "/accountCenter.accountCenterClient/Login"
	AccountCenterClient_PassChange_FullMethodName    = "/accountCenter.accountCenterClient/PassChange"
	AccountCenterClient_CcnuLogin_FullMethodName     = "/accountCenter.accountCenterClient/CcnuLogin"
	AccountCenterClient_BindStudentID_FullMethodName = "/accountCenter.accountCenterClient/BindStudentID"
)

// AccountCenterClientClient is the client API for AccountCenterClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountCenterClientClient interface {
	Register(ctx context.Context, in *RegisterDataReq, opts ...grpc.CallOption) (*RegisterDataResp, error)
	Login(ctx context.Context, in *LoginVerifyReq, opts ...grpc.CallOption) (*LoginVerifyResp, error)
	PassChange(ctx context.Context, in *PassChangeReq, opts ...grpc.CallOption) (*PassChangeResp, error)
	CcnuLogin(ctx context.Context, in *CcnuLoginReq, opts ...grpc.CallOption) (*CcnuLoginResp, error)
	BindStudentID(ctx context.Context, in *BindingStudentIDReq, opts ...grpc.CallOption) (*BindingStudentIDResp, error)
}

type accountCenterClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountCenterClientClient(cc grpc.ClientConnInterface) AccountCenterClientClient {
	return &accountCenterClientClient{cc}
}

func (c *accountCenterClientClient) Register(ctx context.Context, in *RegisterDataReq, opts ...grpc.CallOption) (*RegisterDataResp, error) {
	out := new(RegisterDataResp)
	err := c.cc.Invoke(ctx, AccountCenterClient_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCenterClientClient) Login(ctx context.Context, in *LoginVerifyReq, opts ...grpc.CallOption) (*LoginVerifyResp, error) {
	out := new(LoginVerifyResp)
	err := c.cc.Invoke(ctx, AccountCenterClient_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCenterClientClient) PassChange(ctx context.Context, in *PassChangeReq, opts ...grpc.CallOption) (*PassChangeResp, error) {
	out := new(PassChangeResp)
	err := c.cc.Invoke(ctx, AccountCenterClient_PassChange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCenterClientClient) CcnuLogin(ctx context.Context, in *CcnuLoginReq, opts ...grpc.CallOption) (*CcnuLoginResp, error) {
	out := new(CcnuLoginResp)
	err := c.cc.Invoke(ctx, AccountCenterClient_CcnuLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountCenterClientClient) BindStudentID(ctx context.Context, in *BindingStudentIDReq, opts ...grpc.CallOption) (*BindingStudentIDResp, error) {
	out := new(BindingStudentIDResp)
	err := c.cc.Invoke(ctx, AccountCenterClient_BindStudentID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCenterClientServer is the server API for AccountCenterClient service.
// All implementations must embed UnimplementedAccountCenterClientServer
// for forward compatibility
type AccountCenterClientServer interface {
	Register(context.Context, *RegisterDataReq) (*RegisterDataResp, error)
	Login(context.Context, *LoginVerifyReq) (*LoginVerifyResp, error)
	PassChange(context.Context, *PassChangeReq) (*PassChangeResp, error)
	CcnuLogin(context.Context, *CcnuLoginReq) (*CcnuLoginResp, error)
	BindStudentID(context.Context, *BindingStudentIDReq) (*BindingStudentIDResp, error)
	mustEmbedUnimplementedAccountCenterClientServer()
}

// UnimplementedAccountCenterClientServer must be embedded to have forward compatible implementations.
type UnimplementedAccountCenterClientServer struct {
}

func (UnimplementedAccountCenterClientServer) Register(context.Context, *RegisterDataReq) (*RegisterDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAccountCenterClientServer) Login(context.Context, *LoginVerifyReq) (*LoginVerifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountCenterClientServer) PassChange(context.Context, *PassChangeReq) (*PassChangeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassChange not implemented")
}
func (UnimplementedAccountCenterClientServer) CcnuLogin(context.Context, *CcnuLoginReq) (*CcnuLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CcnuLogin not implemented")
}
func (UnimplementedAccountCenterClientServer) BindStudentID(context.Context, *BindingStudentIDReq) (*BindingStudentIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindStudentID not implemented")
}
func (UnimplementedAccountCenterClientServer) mustEmbedUnimplementedAccountCenterClientServer() {}

// UnsafeAccountCenterClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountCenterClientServer will
// result in compilation errors.
type UnsafeAccountCenterClientServer interface {
	mustEmbedUnimplementedAccountCenterClientServer()
}

func RegisterAccountCenterClientServer(s grpc.ServiceRegistrar, srv AccountCenterClientServer) {
	s.RegisterService(&AccountCenterClient_ServiceDesc, srv)
}

func _AccountCenterClient_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCenterClientServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCenterClient_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCenterClientServer).Register(ctx, req.(*RegisterDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCenterClient_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginVerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCenterClientServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCenterClient_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCenterClientServer).Login(ctx, req.(*LoginVerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCenterClient_PassChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassChangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCenterClientServer).PassChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCenterClient_PassChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCenterClientServer).PassChange(ctx, req.(*PassChangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCenterClient_CcnuLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CcnuLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCenterClientServer).CcnuLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCenterClient_CcnuLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCenterClientServer).CcnuLogin(ctx, req.(*CcnuLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountCenterClient_BindStudentID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindingStudentIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCenterClientServer).BindStudentID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCenterClient_BindStudentID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCenterClientServer).BindStudentID(ctx, req.(*BindingStudentIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountCenterClient_ServiceDesc is the grpc.ServiceDesc for AccountCenterClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountCenterClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accountCenter.accountCenterClient",
	HandlerType: (*AccountCenterClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AccountCenterClient_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccountCenterClient_Login_Handler,
		},
		{
			MethodName: "PassChange",
			Handler:    _AccountCenterClient_PassChange_Handler,
		},
		{
			MethodName: "CcnuLogin",
			Handler:    _AccountCenterClient_CcnuLogin_Handler,
		},
		{
			MethodName: "BindStudentID",
			Handler:    _AccountCenterClient_BindStudentID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accountCenter.proto",
}
