// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.2
// source: accountCenter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *RegisterDataReq) Reset() {
	*x = RegisterDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataReq) ProtoMessage() {}

func (x *RegisterDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataReq.ProtoReflect.Descriptor instead.
func (*RegisterDataReq) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDataReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterDataReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RegisterDataResp) Reset() {
	*x = RegisterDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDataResp) ProtoMessage() {}

func (x *RegisterDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDataResp.ProtoReflect.Descriptor instead.
func (*RegisterDataResp) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDataResp) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type LoginVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *LoginVerifyReq) Reset() {
	*x = LoginVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyReq) ProtoMessage() {}

func (x *LoginVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyReq.ProtoReflect.Descriptor instead.
func (*LoginVerifyReq) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{2}
}

func (x *LoginVerifyReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginVerifyReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *LoginVerifyResp) Reset() {
	*x = LoginVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyResp) ProtoMessage() {}

func (x *LoginVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyResp.ProtoReflect.Descriptor instead.
func (*LoginVerifyResp) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{3}
}

func (x *LoginVerifyResp) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type PassChangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *PassChangeReq) Reset() {
	*x = PassChangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassChangeReq) ProtoMessage() {}

func (x *PassChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassChangeReq.ProtoReflect.Descriptor instead.
func (*PassChangeReq) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{4}
}

func (x *PassChangeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PassChangeReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PassChangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
}

func (x *PassChangeResp) Reset() {
	*x = PassChangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PassChangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassChangeResp) ProtoMessage() {}

func (x *PassChangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassChangeResp.ProtoReflect.Descriptor instead.
func (*PassChangeResp) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{5}
}

func (x *PassChangeResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type CcnuLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentID string `protobuf:"bytes,1,opt,name=StudentID,proto3" json:"StudentID,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *CcnuLoginReq) Reset() {
	*x = CcnuLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CcnuLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcnuLoginReq) ProtoMessage() {}

func (x *CcnuLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcnuLoginReq.ProtoReflect.Descriptor instead.
func (*CcnuLoginReq) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{6}
}

func (x *CcnuLoginReq) GetStudentID() string {
	if x != nil {
		return x.StudentID
	}
	return ""
}

func (x *CcnuLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CcnuLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserinfoID string `protobuf:"bytes,1,opt,name=UserinfoID,proto3" json:"UserinfoID,omitempty"`
}

func (x *CcnuLoginResp) Reset() {
	*x = CcnuLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CcnuLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CcnuLoginResp) ProtoMessage() {}

func (x *CcnuLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CcnuLoginResp.ProtoReflect.Descriptor instead.
func (*CcnuLoginResp) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{7}
}

func (x *CcnuLoginResp) GetUserinfoID() string {
	if x != nil {
		return x.UserinfoID
	}
	return ""
}

type BindingStudentIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StudentID string `protobuf:"bytes,2,opt,name=StudentID,proto3" json:"StudentID,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *BindingStudentIDReq) Reset() {
	*x = BindingStudentIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingStudentIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingStudentIDReq) ProtoMessage() {}

func (x *BindingStudentIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingStudentIDReq.ProtoReflect.Descriptor instead.
func (*BindingStudentIDReq) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{8}
}

func (x *BindingStudentIDReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BindingStudentIDReq) GetStudentID() string {
	if x != nil {
		return x.StudentID
	}
	return ""
}

func (x *BindingStudentIDReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BindingStudentIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
}

func (x *BindingStudentIDResp) Reset() {
	*x = BindingStudentIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountCenter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindingStudentIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingStudentIDResp) ProtoMessage() {}

func (x *BindingStudentIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_accountCenter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingStudentIDResp.ProtoReflect.Descriptor instead.
func (*BindingStudentIDResp) Descriptor() ([]byte, []int) {
	return file_accountCenter_proto_rawDescGZIP(), []int{9}
}

func (x *BindingStudentIDResp) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_accountCenter_proto protoreflect.FileDescriptor

var file_accountCenter_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x42, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x21, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x0d, 0x50, 0x61, 0x73, 0x73, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x50, 0x61, 0x73, 0x73, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x48, 0x0a,
	0x0c, 0x43, 0x63, 0x6e, 0x75, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x43, 0x63, 0x6e, 0x75, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72,
	0x69, 0x6e, 0x66, 0x6f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x49, 0x44, 0x22, 0x67, 0x0a, 0x13, 0x42, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x2a, 0x0a, 0x14, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x32, 0x97, 0x03,
	0x0a, 0x13, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x1e, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x46, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0a, 0x50, 0x61,
	0x73, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x09, 0x43, 0x63, 0x6e, 0x75, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x43, 0x63, 0x6e, 0x75, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x63, 0x6e, 0x75, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x58, 0x0a,
	0x0d, 0x42, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x22,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accountCenter_proto_rawDescOnce sync.Once
	file_accountCenter_proto_rawDescData = file_accountCenter_proto_rawDesc
)

func file_accountCenter_proto_rawDescGZIP() []byte {
	file_accountCenter_proto_rawDescOnce.Do(func() {
		file_accountCenter_proto_rawDescData = protoimpl.X.CompressGZIP(file_accountCenter_proto_rawDescData)
	})
	return file_accountCenter_proto_rawDescData
}

var file_accountCenter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_accountCenter_proto_goTypes = []interface{}{
	(*RegisterDataReq)(nil),      // 0: accountCenter.RegisterDataReq
	(*RegisterDataResp)(nil),     // 1: accountCenter.RegisterDataResp
	(*LoginVerifyReq)(nil),       // 2: accountCenter.LoginVerifyReq
	(*LoginVerifyResp)(nil),      // 3: accountCenter.LoginVerifyResp
	(*PassChangeReq)(nil),        // 4: accountCenter.PassChangeReq
	(*PassChangeResp)(nil),       // 5: accountCenter.PassChangeResp
	(*CcnuLoginReq)(nil),         // 6: accountCenter.CcnuLoginReq
	(*CcnuLoginResp)(nil),        // 7: accountCenter.CcnuLoginResp
	(*BindingStudentIDReq)(nil),  // 8: accountCenter.BindingStudentIDReq
	(*BindingStudentIDResp)(nil), // 9: accountCenter.BindingStudentIDResp
}
var file_accountCenter_proto_depIdxs = []int32{
	0, // 0: accountCenter.accountCenterClient.Register:input_type -> accountCenter.RegisterDataReq
	2, // 1: accountCenter.accountCenterClient.Login:input_type -> accountCenter.LoginVerifyReq
	4, // 2: accountCenter.accountCenterClient.PassChange:input_type -> accountCenter.PassChangeReq
	6, // 3: accountCenter.accountCenterClient.CcnuLogin:input_type -> accountCenter.CcnuLoginReq
	8, // 4: accountCenter.accountCenterClient.BindStudentID:input_type -> accountCenter.BindingStudentIDReq
	1, // 5: accountCenter.accountCenterClient.Register:output_type -> accountCenter.RegisterDataResp
	3, // 6: accountCenter.accountCenterClient.Login:output_type -> accountCenter.LoginVerifyResp
	5, // 7: accountCenter.accountCenterClient.PassChange:output_type -> accountCenter.PassChangeResp
	7, // 8: accountCenter.accountCenterClient.CcnuLogin:output_type -> accountCenter.CcnuLoginResp
	9, // 9: accountCenter.accountCenterClient.BindStudentID:output_type -> accountCenter.BindingStudentIDResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accountCenter_proto_init() }
func file_accountCenter_proto_init() {
	if File_accountCenter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accountCenter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassChangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PassChangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CcnuLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CcnuLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingStudentIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountCenter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindingStudentIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accountCenter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accountCenter_proto_goTypes,
		DependencyIndexes: file_accountCenter_proto_depIdxs,
		MessageInfos:      file_accountCenter_proto_msgTypes,
	}.Build()
	File_accountCenter_proto = out.File
	file_accountCenter_proto_rawDesc = nil
	file_accountCenter_proto_goTypes = nil
	file_accountCenter_proto_depIdxs = nil
}
