// Code generated by goctl. DO NOT EDIT.
package types

type GetUserInfoReq struct {
	Authorization string `header:"Authorization"`
	UserId        string `path:"id"`
}

type GetUserInfoResp struct {
	Avatar    string `json:"avatar"`
	NickName  string `json:"nickname"`
	Email     string `json:"email"`
	Group     string `json:"group"`
	StudentID string `json:"student_id"`
}

type GetReviewReq struct {
	Authorization string `header:"Authorization"`
	Year          int    `json:"year"`
	Group         string `json:"group"`
	Page          int64  `json:"page"`
}

type Row struct {
	Name    string `json:"name"`
	Grade   string `json:"grader"`
	College string `json:"college"`
	Group   string `json:"group"`
	Status  string `json:"status"`
}

type GetReviewResp struct {
	Rows []Row `json:"rows"`
}
