// Code generated by goctl. DO NOT EDIT.
// Source: form.proto

package entryformclient

import (
	"context"

	"MuXiFresh-Be-2.0/app/form/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckReq   = pb.CheckReq
	CheckResp  = pb.CheckResp
	ClickReq   = pb.ClickReq
	ClickResp  = pb.ClickResp
	CreateReq  = pb.CreateReq
	CreateResp = pb.CreateResp

	EntryFormClient interface {
		JudgeUser(ctx context.Context, in *ClickReq, opts ...grpc.CallOption) (*ClickResp, error)
		CreateForm(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		UpdateForm(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
		CheckForm(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
	}

	defaultEntryFormClient struct {
		cli zrpc.Client
	}
)

func NewEntryFormClient(cli zrpc.Client) EntryFormClient {
	return &defaultEntryFormClient{
		cli: cli,
	}
}

func (m *defaultEntryFormClient) JudgeUser(ctx context.Context, in *ClickReq, opts ...grpc.CallOption) (*ClickResp, error) {
	client := pb.NewEntryFormClientClient(m.cli.Conn())
	return client.JudgeUser(ctx, in, opts...)
}

func (m *defaultEntryFormClient) CreateForm(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := pb.NewEntryFormClientClient(m.cli.Conn())
	return client.CreateForm(ctx, in, opts...)
}

func (m *defaultEntryFormClient) UpdateForm(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	client := pb.NewEntryFormClientClient(m.cli.Conn())
	return client.UpdateForm(ctx, in, opts...)
}

func (m *defaultEntryFormClient) CheckForm(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	client := pb.NewEntryFormClientClient(m.cli.Conn())
	return client.CheckForm(ctx, in, opts...)
}
