// Code generated by goctl. DO NOT EDIT.
// Source: schedule.proto

package server

import (
	"context"

	"MuxiFresh2.0/MuXiFresh-Be-2.0/app/schedule/rpc/internal/logic"
	"MuxiFresh2.0/MuXiFresh-Be-2.0/app/schedule/rpc/internal/svc"
	"MuxiFresh2.0/MuXiFresh-Be-2.0/app/schedule/rpc/pb"
)

type ScheduleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedScheduleServer
}

func NewScheduleServer(svcCtx *svc.ServiceContext) *ScheduleServer {
	return &ScheduleServer{
		svcCtx: svcCtx,
	}
}

func (s *ScheduleServer) Check(ctx context.Context, in *pb.CheckReq) (*pb.CheckResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
