// Code generated by goctl. DO NOT EDIT.
// Source: schedule.proto

package server

import (
	"context"

	"MuXiFresh-Be-2.0/app/schedule/rpc/internal/logic"
	"MuXiFresh-Be-2.0/app/schedule/rpc/internal/svc"
	"MuXiFresh-Be-2.0/app/schedule/rpc/pb"
)

type ScheduleClientServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedScheduleClientServer
}

func NewScheduleClientServer(svcCtx *svc.ServiceContext) *ScheduleClientServer {
	return &ScheduleClientServer{
		svcCtx: svcCtx,
	}
}

func (s *ScheduleClientServer) Check(ctx context.Context, in *pb.CheckReq) (*pb.CheckResp, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}

func (s *ScheduleClientServer) Create(ctx context.Context, in *pb.CreateReq) (*pb.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
