// Code generated by goctl. DO NOT EDIT.
package types

type GroupIntroReq struct {
	Authorization string `json:"Authorization"`
	GroupName     string `json:"group_name"`
}

type GroupIntroResp struct {
	Intro string `json:"intro"`
}

type RecruitInfoReq struct {
	Authorization string `json:"Authorization"`
	URL           string `json:"url"`
}

type RecruitInfoResp struct {
	Info string `json:"info"`
}
