// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: form.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 判断身份
type ClickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *ClickReq) Reset() {
	*x = ClickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickReq) ProtoMessage() {}

func (x *ClickReq) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickReq.ProtoReflect.Descriptor instead.
func (*ClickReq) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{0}
}

func (x *ClickReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ClickResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserType   string `protobuf:"bytes,1,opt,name=UserType,proto3" json:"UserType,omitempty"`
	FormStatus string `protobuf:"bytes,2,opt,name=FormStatus,proto3" json:"FormStatus,omitempty"`
}

func (x *ClickResp) Reset() {
	*x = ClickResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResp) ProtoMessage() {}

func (x *ClickResp) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResp.ProtoReflect.Descriptor instead.
func (*ClickResp) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{1}
}

func (x *ClickResp) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *ClickResp) GetFormStatus() string {
	if x != nil {
		return x.FormStatus
	}
	return ""
}

// 提交报名表
type CreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        string `protobuf:"bytes,12,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FormId        string `protobuf:"bytes,13,opt,name=FormId,proto3" json:"FormId,omitempty"`
	Token         string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Avatar        string `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Major         string `protobuf:"bytes,3,opt,name=Major,proto3" json:"Major,omitempty"`
	Grade         string `protobuf:"bytes,4,opt,name=Grade,proto3" json:"Grade,omitempty"`
	Gender        string `protobuf:"bytes,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Phone         string `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Group         string `protobuf:"bytes,7,opt,name=Group,proto3" json:"Group,omitempty"`
	Reason        string `protobuf:"bytes,8,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Knowledge     string `protobuf:"bytes,9,opt,name=Knowledge,proto3" json:"Knowledge,omitempty"`
	SelfIntro     string `protobuf:"bytes,10,opt,name=SelfIntro,proto3" json:"SelfIntro,omitempty"`
	ExtraQuestion string `protobuf:"bytes,11,opt,name=ExtraQuestion,proto3" json:"ExtraQuestion,omitempty"`
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReq) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *CreateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateReq) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *CreateReq) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *CreateReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateReq) GetKnowledge() string {
	if x != nil {
		return x.Knowledge
	}
	return ""
}

func (x *CreateReq) GetSelfIntro() string {
	if x != nil {
		return x.SelfIntro
	}
	return ""
}

func (x *CreateReq) GetExtraQuestion() string {
	if x != nil {
		return x.ExtraQuestion
	}
	return ""
}

type CreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormID string `protobuf:"bytes,1,opt,name=FormID,proto3" json:"FormID,omitempty"`
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResp) GetFormID() string {
	if x != nil {
		return x.FormID
	}
	return ""
}

// 查看报名表
type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	EntryFormID string `protobuf:"bytes,2,opt,name=EntryFormID,proto3" json:"EntryFormID,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{4}
}

func (x *CheckReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckReq) GetEntryFormID() string {
	if x != nil {
		return x.EntryFormID
	}
	return ""
}

type CheckResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar        string `protobuf:"bytes,1,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Major         string `protobuf:"bytes,2,opt,name=Major,proto3" json:"Major,omitempty"`
	Grade         string `protobuf:"bytes,3,opt,name=Grade,proto3" json:"Grade,omitempty"`
	Gender        string `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Phone         string `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Group         string `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	Reason        string `protobuf:"bytes,7,opt,name=Reason,proto3" json:"Reason,omitempty"`
	Knowledge     string `protobuf:"bytes,8,opt,name=Knowledge,proto3" json:"Knowledge,omitempty"`
	SelfIntro     string `protobuf:"bytes,9,opt,name=SelfIntro,proto3" json:"SelfIntro,omitempty"`
	ExtraQuestion string `protobuf:"bytes,10,opt,name=ExtraQuestion,proto3" json:"ExtraQuestion,omitempty"`
}

func (x *CheckResp) Reset() {
	*x = CheckResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResp) ProtoMessage() {}

func (x *CheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResp.ProtoReflect.Descriptor instead.
func (*CheckResp) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CheckResp) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *CheckResp) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *CheckResp) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CheckResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CheckResp) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CheckResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckResp) GetKnowledge() string {
	if x != nil {
		return x.Knowledge
	}
	return ""
}

func (x *CheckResp) GetSelfIntro() string {
	if x != nil {
		return x.SelfIntro
	}
	return ""
}

func (x *CheckResp) GetExtraQuestion() string {
	if x != nil {
		return x.ExtraQuestion
	}
	return ""
}

type GetApplicantNumberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  string `protobuf:"bytes,1,opt,name=Group,proto3" json:"Group,omitempty"`
	Year   int64  `protobuf:"varint,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Season string `protobuf:"bytes,3,opt,name=Season,proto3" json:"Season,omitempty"`
}

func (x *GetApplicantNumberReq) Reset() {
	*x = GetApplicantNumberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicantNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantNumberReq) ProtoMessage() {}

func (x *GetApplicantNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantNumberReq.ProtoReflect.Descriptor instead.
func (*GetApplicantNumberReq) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{6}
}

func (x *GetApplicantNumberReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetApplicantNumberReq) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetApplicantNumberReq) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

type GetApplicantNumberResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
}

func (x *GetApplicantNumberResp) Reset() {
	*x = GetApplicantNumberResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_form_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApplicantNumberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicantNumberResp) ProtoMessage() {}

func (x *GetApplicantNumberResp) ProtoReflect() protoreflect.Message {
	mi := &file_form_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicantNumberResp.ProtoReflect.Descriptor instead.
func (*GetApplicantNumberResp) Descriptor() ([]byte, []int) {
	return file_form_proto_rawDescGZIP(), []int{7}
}

func (x *GetApplicantNumberResp) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_form_proto protoreflect.FileDescriptor

var file_form_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x22, 0x20, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x47, 0x0a, 0x09, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xd3, 0x02,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x6a,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x66, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x6c, 0x66, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x24, 0x0a,
	0x0d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x08, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x22, 0x8d, 0x02,
	0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6c,
	0x66, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65,
	0x6c, 0x66, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x59, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x59, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xa0, 0x02, 0x0a, 0x0f, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x2c,
	0x0a, 0x09, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x0f, 0x2e, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x0f, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c,
	0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x0e, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1b, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_form_proto_rawDescOnce sync.Once
	file_form_proto_rawDescData = file_form_proto_rawDesc
)

func file_form_proto_rawDescGZIP() []byte {
	file_form_proto_rawDescOnce.Do(func() {
		file_form_proto_rawDescData = protoimpl.X.CompressGZIP(file_form_proto_rawDescData)
	})
	return file_form_proto_rawDescData
}

var file_form_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_form_proto_goTypes = []interface{}{
	(*ClickReq)(nil),               // 0: form.ClickReq
	(*ClickResp)(nil),              // 1: form.ClickResp
	(*CreateReq)(nil),              // 2: form.CreateReq
	(*CreateResp)(nil),             // 3: form.CreateResp
	(*CheckReq)(nil),               // 4: form.CheckReq
	(*CheckResp)(nil),              // 5: form.CheckResp
	(*GetApplicantNumberReq)(nil),  // 6: form.GetApplicantNumberReq
	(*GetApplicantNumberResp)(nil), // 7: form.GetApplicantNumberResp
}
var file_form_proto_depIdxs = []int32{
	0, // 0: form.EntryFormClient.JudgeUser:input_type -> form.ClickReq
	2, // 1: form.EntryFormClient.CreateForm:input_type -> form.CreateReq
	2, // 2: form.EntryFormClient.UpdateForm:input_type -> form.CreateReq
	4, // 3: form.EntryFormClient.CheckForm:input_type -> form.CheckReq
	6, // 4: form.EntryFormClient.GetApplicantNumber:input_type -> form.GetApplicantNumberReq
	1, // 5: form.EntryFormClient.JudgeUser:output_type -> form.ClickResp
	3, // 6: form.EntryFormClient.CreateForm:output_type -> form.CreateResp
	3, // 7: form.EntryFormClient.UpdateForm:output_type -> form.CreateResp
	5, // 8: form.EntryFormClient.CheckForm:output_type -> form.CheckResp
	7, // 9: form.EntryFormClient.GetApplicantNumber:output_type -> form.GetApplicantNumberResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_form_proto_init() }
func file_form_proto_init() {
	if File_form_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_form_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicantNumberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_form_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApplicantNumberResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_form_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_form_proto_goTypes,
		DependencyIndexes: file_form_proto_depIdxs,
		MessageInfos:      file_form_proto_msgTypes,
	}.Build()
	File_form_proto = out.File
	file_form_proto_rawDesc = nil
	file_form_proto_goTypes = nil
	file_form_proto_depIdxs = nil
}
