// Code generated by goctl. DO NOT EDIT.
package types

type AdjustAdmissionstatusReq struct {
	Authorization   string `header:"Authorization"`
	AdmissionStatus string `path:"AdmissionStatus"`
}

type AdjustAdmissionstatusResp struct {
	Flag bool `json:"flag"`
}

type ModifytheUsertypeReq struct {
	Authorization string `header:"Authorization"`
	Email         string `json:"Email"`
	UserType      string `json:"UserType"`
}

type ModifytheUsertypeResp struct {
	Flag bool `json:"flag"`
}

type ModifytheUseravatarReq struct {
	Authorization string `header:"Authorization"`
	Avatar        string `json:"Avatar"`
}

type ModifytheUseravatarResp struct {
	Flag bool `json:"flag"`
}

type ModifytheUsernameReq struct {
	Authorization string `header:"Authorization"`
	NickName      string `json:"NickName"`
}

type ModifytheUsernameResp struct {
	Flag bool `json:"flag"`
}
