// Code generated by goctl. DO NOT EDIT.
// Source: modify.proto

package modifyClient

import (
	"context"

	"MuXiFresh-Be-2.0/app/modify/cmd/rpc/modify/modify"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ModifytheUseravatarReq  = modify.ModifytheUseravatarReq
	ModifytheUseravatarResp = modify.ModifytheUseravatarResp
	ModifytheUsernameReq    = modify.ModifytheUsernameReq
	ModifytheUsernameResp   = modify.ModifytheUsernameResp
	ModifytheUsertypeReq    = modify.ModifytheUsertypeReq
	ModifytheUsertypeResp   = modify.ModifytheUsertypeResp

	Modify interface {
		ModifytheUsertype(ctx context.Context, in *ModifytheUsertypeReq, opts ...grpc.CallOption) (*ModifytheUsertypeResp, error)
		ModifytheUseravatar(ctx context.Context, in *ModifytheUseravatarReq, opts ...grpc.CallOption) (*ModifytheUseravatarResp, error)
		ModifytheUsername(ctx context.Context, in *ModifytheUsernameReq, opts ...grpc.CallOption) (*ModifytheUsernameResp, error)
	}

	defaultModify struct {
		cli zrpc.Client
	}
)

func NewModify(cli zrpc.Client) Modify {
	return &defaultModify{
		cli: cli,
	}
}

func (m *defaultModify) ModifytheUsertype(ctx context.Context, in *ModifytheUsertypeReq, opts ...grpc.CallOption) (*ModifytheUsertypeResp, error) {
	client := modify.NewModifyClient(m.cli.Conn())
	return client.ModifytheUsertype(ctx, in, opts...)
}

func (m *defaultModify) ModifytheUseravatar(ctx context.Context, in *ModifytheUseravatarReq, opts ...grpc.CallOption) (*ModifytheUseravatarResp, error) {
	client := modify.NewModifyClient(m.cli.Conn())
	return client.ModifytheUseravatar(ctx, in, opts...)
}

func (m *defaultModify) ModifytheUsername(ctx context.Context, in *ModifytheUsernameReq, opts ...grpc.CallOption) (*ModifytheUsernameResp, error) {
	client := modify.NewModifyClient(m.cli.Conn())
	return client.ModifytheUsername(ctx, in, opts...)
}
