// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ccnulogin "MuXiFresh-Be-2.0/app/userauth/cmd/api/internal/handler/ccnulogin"
	"MuXiFresh-Be-2.0/app/userauth/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/authorize-password-change",
				Handler: AuthPassChangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send-verification-code",
				Handler: SendVerificationCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get-captcha",
				Handler: GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verify-captcha",
				Handler: VerifyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/get-qntoken",
				Handler: GetQNTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/password-change",
				Handler: PassChangeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuthChPass.AccessSecret),
		rest.WithPrefix("/api/v2/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bind-student-id",
				Handler: ccnulogin.BindStudentIDHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v2/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ccnuLogin",
				Handler: ccnulogin.CcnuLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2/auth"),
	)
}
